server:
  port: 8080
spring:
  datasource:
    url: jdbc:sqlite:sample.db
    driverClassName: org.sqlite.JDBC
#    initialization-mode: always

  jpa:
    database-platform: com.jumia.jpay.jpayvalidator.configuration.SqlLiteDialect
    hibernate:
      ddl-auto: update
